### ISSUE TITLE
Unable to use SQLite InMemory

### ISSUE THREAD

**Issue by meziantou** [smourier/SQLNado#1]
SQLite has an [In-Memory](https://www.sqlite.org/inmemorydb.html) mode which is very useful for testing an application. `SQLNado` doesn't support it currently because it expects a valid file path (`Path.GetFullPath(filePath)`).

Repro:
```
new SQLiteDatabase(":memory:")
```

I think removing the line `filePath = Path.GetFullPath(filePath);` will fix the issue.

BTW, I think there is the same issue with temporary databases `new SQLiteDatabase("")`.

**Comment by smourier** [comment]
Done.
