### ISSUE TITLE
How to use prepared statement

### ISSUE THREAD

**Issue by dunha** [smourier/SQLNado#10]
Your examples show database access within a using statement, and I know this is the preferred method for IDisposable.  However, I'd like to open the database and leave it open while the app is running for continual access, then close the connection when the app closes, preferably using a single prepared statement and binding new parameters (GPS coords) at each access.
I wasn't able to determine how to reuse a prepared statement. Is it supported?

**Comment by smourier** [comment]
Hi,

Sure, you can use the `SQLiteDatabase.PrepareStatement` method (https://github.com/smourier/SQLNado/blob/master/SqlNado/SQLiteDatabase.cs#L1742)

By default, prepared statements are also cached. This is governed by the `EnableStatementsCache ` property (https://github.com/smourier/SQLNado/blob/master/SqlNado/SQLiteDatabase.cs#L117) which should be set to `true` by default.

**Comment by dunha** [comment]
Wow. Thanks for the speedy reply.
I discovered this, but embarrassingly, I'm not sure how to use the statement and rebind the parameters

**Comment by smourier** [comment]
Just have a look at SQLiteDatabase.cs and search for PrepareStatement, you'll see how it can be used.

**Comment by dunha** [comment]
Sorry, I just don't see how the statement is executed. 
Also I discovered the title was for another issue I resolved. Updated

**Comment by dunha** [comment]
I get it now. Thanks
