### ISSUE TITLE
What do I pass to args in Load<T>(string sql, params object[] args)?

### ISSUE THREAD

**Issue by Jeshibu** [smourier/SQLNado#11]
I'm looking to do a projection query - that is, a string query with parameters that gets its result returned as objects of a specified type. I think `Load<T>(string sql, params object[] args)` should be that, but I'm unsure what to pass to the `args` parameter there. `DbParameter` derived class instances? `KeyValuePair`s? Tuples? Or is it just the parameter values?

And how do I refer to these parameters in the query, in case it's just the parameter values?

**Comment by smourier** [comment]
Hi,

Yes, it's just the parameter values, like this:

```
using (var db = new SQLiteDatabase(":memory:"))
{
    int max = 10;
    for (int i = 0; i < max; i++)
    {
        var customer = new Customer1();
        customer.Id = i;
        customer.Name = (i % 2) == 0 ? "Even" + i : "Odd" + i;
        db.Save(customer);
    }

    var evens = db.Load<Customer1>("WHERE name LIKE ?", "Even%").ToArray();
    Assert.AreEqual(5, evens.Length);

    var odds = db.Load<Customer1>("WHERE name LIKE ?", "Odd%").ToArray();
    Assert.AreEqual(5, odds.Length);
}

[SQLiteTable(Name = "Customer")]
private sealed class Customer1
{
    public int Id { get; set; }
    public string Name { get; set; }

    public override string ToString() => Name;
}
```

PS: SQLNado is not based on ADO.NET so there's no concept of "DbParameter" here.

**Comment by Jeshibu** [comment]
Thank you!
