### ISSUE TITLE
A way to specify table names for generic types

### ISSUE THREAD

**Issue by JosefNemec** [smourier/SQLNado#12]
Is there any other way to set table name for a type other than using `SQLiteTable` attribute? I'm having an issue with storing generic types. Since they are generic, I can't assign this attribute to them and name that's automatically generated by SQLNado is not usable since it's the same name for all resulting types. For example:

```csharp
public class DbStoreItem<T>
{
}

db.Save<DbStoreItem<TypeA>>(itemA);
db.Save<DbStoreItem<TypeB>>(itemB);
```

This results in only one table being created, called ``DbStoreItem`1``, with both items stored in the same table.

I want somehow specify that `DbStoreItem<TypeA>` items should be in a table called `TypeAItems` and similar for TypeB.

The only way I found is defining "wrapper" types with SQLiteTable attribute, but that's obviously not ideal since it's add a lot of boilerplate:
```csharp
[SQLiteTable(Name = "TypeAItems")]
public class TypeAItem : DbStoreItem<TypeA>
{
}
```

**Comment by smourier** [comment]
Hi,

Sure there's a way, you need to override `SQLiteDatabase`, something like this:

    public class GenericsDatabase : SQLiteDatabase
    {
        public GenericsDatabase(string filePath, SQLiteOpenOptions options = SQLiteOpenOptions.SQLITE_OPEN_READWRITE | SQLiteOpenOptions.SQLITE_OPEN_CREATE)
            : base(filePath, options)
        {
        }

        protected override SQLiteObjectTableBuilder CreateObjectTableBuilder(Type type, SQLiteBuildTableOptions options = null) => new GenericsSQLiteObjectTableBuilder(this, type, options);
        private class GenericsSQLiteObjectTableBuilder : SQLiteObjectTableBuilder
        {
            public GenericsSQLiteObjectTableBuilder(GenericsDatabase database, Type type, SQLiteBuildTableOptions options = null)
                : base(database, type, options)
            {
                var genericArguments = type.GenericTypeArguments;
                if (genericArguments.Length > 0)
                {
                    // come up with some smart name (or use some attribute somewhere)
                    GenericName = type.Name + "_" + string.Join("_", genericArguments.Select(a => a.Name));
                }
            }

            public string GenericName { get; }
            protected override SQLiteObjectTable CreateObjectTable(string name)
            {
                if (GenericName != null)
                {
                    name = GenericName;
                }
                return base.CreateObjectTable(name);
            }
        }
    }

Now, this type of code:

    using (var db = new GenericsDatabase("generics.db"))
    {
        var itemA = new DbStoreItem<TypeA>();
        var itemB = new DbStoreItem<TypeB>();

        db.Save(itemA);
        db.Save(itemB);
    }

will create two tables: `DbStoreItem'1_TypeA` and `DbStoreItem'1_TypeB` (you can change my code to generate something different) while keeping non generic tables behavior.

**Comment by JosefNemec** [comment]
Works great, thanks a lot!
