### ISSUE TITLE
how to create tables based on class?

### ISSUE THREAD

**Issue by immayankmodi** [smourier/SQLNado#3]
Hi,

I'm just trying to use your wrapper and it looks great. I've noticed:

- Save method automatically create database and tables if not exists
- When I tried to call LoadAll<T> before save method and it throws database table not found exception

Obviously we'have to save records to create tables but what if we want to get list first? We can create table here as well so it won't throw exception. OR let me know if there is any workaround to overcome this issue with your wrapper??

Regards

**Comment by smourier** [comment]
Hi,

Yes, Save creates a table for a given type if it does not exists. This is in fact optional, but enabled by default when saving one object, disabled by default when saving multiple objects.

However, it won't create a table when reading from a database, but you can do that using the SynchronizeSchema method. Sample code:

    using (var db = new SQLiteDatabase(":memory:")) // an in-memory database, useful for tests
    {
        // ask SqlNado to synchronize the table with the current object layout
        db.SynchronizeSchema<MyClass>();
        var all = db.LoadAll<MyClass>();
    }

You could also test for table existence, like this:

    using (var db = new SQLiteDatabase(":memory:"))
    {
        // check if table exist before running the SELECT
        if (db.TableExists<SimpleUser>())
        {
            var all = db.LoadAll<MyClass>();
        }
    }

**Comment by immayankmodi** [comment]
Thanks, I'll check it and will let you know!
