### ISSUE TITLE
is this project support Encryption for the database

### ISSUE THREAD

**Issue by sndnvaps** [smourier/SQLNado#4]

**Comment by smourier** [comment]
Which encryption? as you know, it's not pure standard in SQLite: https://stackoverflow.com/questions/5669905/sqlite-with-encryption-password-protection
but if the encryption you use is a dropin replacement, if you just have to change the sqlite dll, then it should work

**Comment by sndnvaps** [comment]
enc all the db file. 
not just some key in the db

**Comment by smourier** [comment]
yes, I got that, but like I said, it's not standard with SQLite, so what addon do you target?
