### ISSUE TITLE
Support Compiling on .NET v3.5?

### ISSUE THREAD

**Issue by spaceman5** [smourier/SQLNado#5]
Hi

Is it possible to make SQLNado's code to be able to compile under .NET v3.5?

**Comment by smourier** [comment]
Hi,

No, the minimum target framework is 4.6 (or netstandard 2). It could be modified to support 4.5, but it would require too much work to support 3.5.

It's quite easy to test, you can get the SqlNado.cs file from the Amalgamation folder and see how it compiles.

**Comment by spaceman5** [comment]
>the minimum target framework is 4.6 (or netstandard 2).
>It could be modified to support 4.5,
>but it would require too much work to support 3.5.

Is it possible that if one gives up some components (like ORM and such) then v3.5 will not be too much of a change?

(I don't need ORM, async, or anything like that, just basic SQL queries and that's it..)



>It's quite easy to test,
> you can get the SqlNado.cs file from the Amalgamation folder and see how it compiles.

Tried now..
426 Errors.. :)
So no luck for me..
